sellnbuy/about/urls.py
from . import views
from django.urls import path

app_name = 'about'

urlpatterns = [
    path('about-author', views.author_page, name='author_page'),
    path('techs', views.techs, name='techs')
]

sellnbuy/sellnbuy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('users.urls')),
    path('', include('supplies.urls')),
    path('', include('about.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellnbuy/users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, LoginView, \
    LogoutView

app_name = "users"

urlpatterns = [
    path('sign-up', views.SignUp.as_view(), name='sign_up'),
    path('password-reset', PasswordResetView.as_view(template_name="users/password_reset.html", success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset-done', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('login', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    ]

sellnbuy/users/models.py
from django.db import models

# Create your models here.

sellnbuy/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

User = get_user_model()


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50, label="Имя")
    last_name = forms.CharField(max_length=50, label="Фамилия")
    phone = forms.CharField(max_length=18, label="Телефонный номер")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone', 'password1', 'password2']

sellnbuy/users/views.py
from django.urls import reverse_lazy
from .forms import UserRegistrationForm
from django.views.generic import CreateView

# Create your views here.


class SignUp(CreateView): #переделать?
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

sellnbuy/templates/users/login.html
{% extends "form-background.html" %}
{% block content %}
<header class="form-header">Вход в аккаунт</header>
<form method="POST" class="form">
    {% csrf_token %}
    {% for field in form %}
    <div class="input-box">
        <label>{{ field.label_tag }}</label>
        <div>{{ field }}</div>
        {% if field.errors %}
        {% for error in field.errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <section class="non-field-errors">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </section>
    <div class="forgot-password">
        <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
    </div>
    <button type="submit" class="form-button">Войти в аккаунт</button>
</form>
{% endblock %}

sellnbuy/templates/users/password_reset.html
{% extends "form-background.html" %}
{% block content %}
<header class="form-header">Восстановление пароля</header>
<form method="POST" class="form">
    {% csrf_token %}
    <div class="input-box">
        <label>{{ form.email.label_tag }}</label>
        <div>{{ form.email }}</div>
        {% if form.email.errors %}
        {% for error in form.email.errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </div>
    <section class="non-field-errors">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </section>
    <button type="submit" class="form-button">Подтвердить</button>
</form>
{% endblock %}

sellnbuy/templates/users/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

sellnbuy/templates/users/password_reset_done.html
{% extends "form-background.html" %}
{% block content %}
<header class="form-header">Письмо с инструкциями по восстановлению пароля отправлено</header>
<div>
    <a>Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.</a>
</div>
<div>
    <a>Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</a>
</div>
{% endblock %}

sellnbuy/templates/users/signup.html
{% extends "form-background.html" %}
{% block content %}
<header class="form-header">Регистрация пользователя</header>
<form method="POST" class="form">
    {% csrf_token %}
    {% for field in form %}
    <div class="input-box">
        <label>{{ field.label_tag }}</label>
        <div>{{ field }}</div>
        {% if field.errors %}
        {% for error in field.errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <section class="non-field-errors">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </section>
    <button type="submit" class="form-button">Создать аккаунт</button>
</form>
{% endblock %}