sellnbuy/about/urls.py
from . import views
from django.urls import path

app_name = 'about'

urlpatterns = [
    path('about-author', views.author_page, name='author_page'),
    path('techs', views.techs, name='techs')
]

sellnbuy/sellnbuy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('users.urls')),
    path('', include('supplies.urls')),
    path('', include('about.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellnbuy/supplies/urls.py
from django.urls import path
from . import views

app_name = "supplies"

urlpatterns = [
    path('', views.main, name='index'),
    path('add-supply/', views.add_supply, name='add_supply'),
    path('messanger', views.messanger, name='messanger'),
    path('<int:id>/', views.view_supply, name='supply'),
    path('<int:id>/comment', views.add_comment, name='add_comment'),
    path('change-supply/<int:id>', views.change_supply, name='change_supply'),
    path('delete-supply/<int:id>', views.delete_supply, name='delete_supply'),
    path('change-comment/<int:id>', views.change_comment, name='change_comment'),
    path('delete-comment/<int:id>', views.delete_comment, name='delete_comment'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/chat', views.open_chat, name='chat'),
    path('<str:username>/chat/send-message', views.send_message, name='send_message'),
    ]

sellnbuy/supplies/models.py
from django.db import models
from django.contrib.auth.models import User


class Supply(models.Model):
    user = models.ForeignKey(User, related_name="seller", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    desc = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='supplies/', blank=True, null=True)


class Comment(models.Model):
    rating_value = (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'))
    user = models.ForeignKey(User, related_name="comment_author", on_delete=models.CASCADE)
    rating = models.CharField(max_length=1, choices=rating_value)
    supply = models.ForeignKey(Supply, related_name="post_to_comment", on_delete=models.CASCADE)
    text = models.TextField()


class Message(models.Model):
    user = models.ForeignKey(User, related_name="message_author", on_delete=models.CASCADE)
    to = models.ForeignKey(User, related_name="message_receiver", on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

sellnbuy/supplies/forms.py
from django import forms
from .models import Supply, Comment, Message


class SupplyForm(forms.ModelForm):
    class Meta:
        model = Supply
        fields = ('name', 'price', 'desc', 'image', )
        labels = {
            'name': 'Название товара',
            'price': 'Цена товара',
            'desc': 'Описание товара',
            'image': 'Фотография товара',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('rating', 'text', )
        labels = {
            'rating': 'Ваша оценка',
            'text': 'Текст комментария',
        }


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('text', )
        labels = {
            'text': 'Отправить сообщение пользователю',
        }

sellnbuy/supplies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Supply, User, Comment, Message
from .forms import SupplyForm, CommentForm, MessageForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from . import utils


def main(request):
    paginator = Paginator(Supply.objects.all().order_by('id'), 20)
    page_number = request.GET.get("page") or 1
    page_obj = paginator.get_page(page_number)
    paginator_page_numbers = [i for i in range(int(page_number) - 2, int(page_number) + 3)]
    context = {"page_obj": page_obj, "paginator_page_numbers": paginator_page_numbers, }
    return render(request, "supplies/index.html", context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    user_supplies = Supply.objects.filter(user=user.id).order_by('id')
    count = user_supplies.count
    paginator = Paginator(user_supplies, 20)
    page_number = request.GET.get("page") or 1
    page_obj = paginator.get_page(page_number)
    paginator_page_numbers = [i for i in range(int(page_number) - 2, int(page_number) + 3)]
    context = {"page_obj": page_obj, "user": user, "paginator_page_numbers": paginator_page_numbers, 'count': count}
    return render(request, "supplies/profile.html", context)


def view_supply(request, id):
    form = CommentForm()
    supply = get_object_or_404(Supply, id=id)
    paginator = Paginator(Comment.objects.filter(supply=supply).order_by('-id'), 20)
    page_number = request.GET.get("page") or 1
    page_obj = paginator.get_page(page_number)
    paginator_page_numbers = [i for i in range(int(page_number) - 2, int(page_number) + 3)]
    if request.user.is_authenticated:
        is_user_comment_exists = bool(Comment.objects.filter(supply=supply, user=request.user))
    else:
        is_user_comment_exists = False
    context = {
        "supply": supply,
        "form": form,
        "page_obj": page_obj,
        "paginator_page_numbers": paginator_page_numbers,
        "is_user_comment_exists": is_user_comment_exists,
    }
    return render(request, "supplies/supply_page.html", context)


@login_required
def add_supply(request):
    if request.method == 'POST':
        form = SupplyForm(request.POST or None, files=request.FILES or None)
        if form.is_valid():
            supply = form.save(commit=False)
            supply.user = request.user
            supply.save()
            return redirect('supplies:profile', supply.user)
        return render(request, 'supplies/add_supply.html', {"form": form, 'change': False})
    form = SupplyForm()
    return render(request, 'supplies/add_supply.html', {"form": form, 'change': False})


@login_required
def add_comment(request, id):
    supply = get_object_or_404(Supply, id=id)
    if request.method == "POST":
        form = CommentForm(request.POST or None)
        if form.is_valid() and request.user != supply.user and not Comment.objects.filter(user=request.user,
                                                                                          supply=supply):
            comment = form.save(commit=False)
            comment.user = request.user
            comment.supply = supply
            comment.save()
    return redirect('supplies:supply', id)


@login_required
def send_message(request, username):
    to = get_object_or_404(User, username=username)
    if request.method == "POST":
        form = MessageForm(request.POST or None)
        if form.is_valid() and request.user.username != username:
            message = form.save(commit=False)
            message.user = request.user
            message.to = to
            message.save()
    return redirect('supplies:chat', username)


@login_required
def open_chat(request, username):
    if request.user.username != username:
        to = get_object_or_404(User, username=username)
        form = MessageForm
        messages = utils.Chat(request.user, to).list_of_messages()
        context = {'messages': messages, 'form': form, 'username': username}
        return render(request, 'supplies/chat.html', context)


@login_required
def messanger(request):
    users = set(Message.objects.filter(user=request.user).values_list('to__username', flat=True))
    chat = {}
    chats = []
    for user in users:
        user = User.objects.get(username=user)
        chat['user'] = user.username
        chat['last_message'] = utils.Chat(request.user.id, user.id).get_last_message()
        chats.append(chat)
        chat = {}
    chats.sort(key=lambda chat: chat['last_message'].time.timestamp(), reverse=True)
    return render(request, 'supplies/messanger.html', {'chats': chats})


@login_required
def change_comment(request, id):
    comment = get_object_or_404(Comment, id=id)
    if request.user.id == comment.user.id:
        form = CommentForm(request.POST or None, instance=comment)
        if request.method == "POST":
            if form.is_valid():
                form.save()
            return redirect('supplies:supply', comment.supply.id)
        return render(request, 'supplies/change_comment.html', {"form": form})
    return redirect('supplies:supply', comment.supply.id)


@login_required
def delete_comment(request, id):
    comment = get_object_or_404(Comment, id=id)
    if request.user.id == comment.user.id:
        Comment.objects.filter(id=id).delete()
    return redirect('supplies:supply', comment.supply.id)


@login_required
def change_supply(request, id):
    supply = get_object_or_404(Supply, id=id)
    if request.user.id == supply.user.id:
        form = SupplyForm(request.POST or None, files=request.FILES or None, instance=supply)
        if request.method == "POST":
            if form.is_valid():
                form.save()
            return redirect('supplies:supply', supply.id)
        return render(request, 'supplies/add_supply.html', {"form": form, 'change': True})
    return redirect('supplies:supply', supply.id)


@login_required()
def delete_supply(request, id):
    supply = get_object_or_404(Supply, id=id)
    if request.user.id == supply.user.id:
        Supply.objects.filter(id=id).delete()
        return redirect('supplies:profile', supply.user.username)
    return redirect('supplies:supply', supply.id)

sellnbuy/templates/supplies/add_supply.html
{% extends "form-background.html" %}
{% block content %}
{% if change %}
<header class="form-header">Редактировать объявление</header>
{% else %}
<header class="form-header">Создать объявление</header>
{% endif %}
<form method="POST" enctype="multipart/form-data" class="form">
    {% csrf_token %}
    {% for field in form %}
    <div class="input-box">
        <label>{{ field.label_tag }}</label>
        <div>{{ field }}</div>
        {% if field.errors %}
        {% for error in field.errors %}
          <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <section class="non-field-errors">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </section>
    <div class="form-buttons">
        <button type="cancel" class="form-button" onclick="window.history.back();">Выйти</button>
        {% if change %}
        <button type="submit" class="form-button">Сохранить изменения</button>
        {% else %}
        <button type="submit" class="form-button">Создать объявление</button>
        {% endif %}
    </div>
</form>
{% endblock %}

sellnbuy/templates/supplies/change_comment.html
{% extends "form-background.html" %}
{% block content %}
<header class="form-header">Редактировать комментарий</header>
<form method="POST" class="form">
    {% csrf_token %}
    <div class="input-box">
        <label>{{ form.text.label_tag }}</label>
        <div>{{ form.text }}</div>
        {% if form.email.errors %}
        {% for error in form.email.errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </div>
    <section class="non-field-errors">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </section>
    <div class="form-buttons">
        <button type="cancel" class="form-button" onclick="window.history.back();">Отменить</button>
        <button type="submit" class="form-button">Подтвердить</button>
    </div>
</form>
{% endblock %}

sellnbuy/templates/supplies/chat.html
{% extends 'base.html' %}
{% block content %}
<div class="chat">
{% for message in messages %}
        {% if message.to != request.user %}
            <div class="message">
                <ul class="message-info">
                    <li><a class="link" href="{% url 'supplies:profile' message.user %}">{{ message.user }}</a></li>
                    <li>{{ message.time }}</li>
                </ul>
                <div class="last-message-text">{{ message.text }}</div>
            </div>
        {% else %}
            <div class="message-to">
                <ul class="message-info">
                    <li><a class="link" href="{% url 'supplies:profile' message.user %}">{{ message.user }}</a></li>
                    <li>{{ message.time }}</li>
                </ul>
                <div class="test">
                    <div class="last-message-text">{{ message.text }}</div>
                </div>
            </div>
        {% endif %}
    <hr>
{% endfor %}
</div>
<form method="POST" class="message-form" action="{% url 'supplies:send_message' username %}">
    <div class="input">
        {% csrf_token %}
        {% for field in form %}
        <label>{{ field.label_tag }}</label>
        <div>{{ field }}</div>
        {% if field.errors %}
        {% for error in field.errors %}
          <div class="form-error">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </div>
    {% endfor %}
    <button type="submit" class="message-button">Отправить сообщение</button>
</form>
{% endblock %}

sellnbuy/templates/supplies/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load thumbnail %}
<section class="shop">
    <div class="supplies">
        {% for supply in page_obj %}
            <div class="supply">
                <a class="link" href="{% url 'supplies:supply' supply.id %}">
                    <div>
                        {% if supply.image %}
                        {% thumbnail supply.image "200x200" crop="center" upscale=True as im %}
                            <img class="" src="{{ im.url }}">
                        {% endthumbnail %}
                        {% else %}
                        <img src="{% static 'img/no-image.jpeg' %}" width="200" height="200">
                        {% endif %}
                        <div class="supply_name">{{ supply.name }}</div>
                        <div>Цена товара:</div>
                        <div class="price">{{ supply.price }}</div>
                        <div>Описание товара:</div>
                        <div class="desc">{{ supply.desc }}</div>
                    </div>
                </a>
                <div>Продавец:</div>
                <a class="link" href="{% url 'supplies:profile' supply.user %}">{{ supply.user }}</a>
            </div>
        {% endfor %}
    </div>
    <div class="pagination-grid">
        {% include "includes/paginator.html" %}
    </div>
</section>
{% endblock %}

sellnbuy/templates/supplies/messanger.html
{% extends 'base.html' %}
{% block content %}
{% for chat in chats %}
    <a class="link" href="{% url 'supplies:chat' chat.user %}">
        <div class="chats">
            <div class="last-message-author">{{ chat.user }}</div>
            <div>{{ chat.last_message.text|truncatechars:90 }}</div>
            <div class="last-message-time">{{ chat.last_message.time }}</div>
        </div>
    </a>
    <hr>
{% endfor %}
{% endblock %}

sellnbuy/templates/supplies/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
    <section class="user">
        <div class="user-info">
            <img src="{% static 'img/no-image.jpeg' %}" width="200" height="200">
                <div>Имя:</div>
                <div>{{user.first_name}}</div>
                <div>Фамилия:</div>
                <div>{{user.last_name}}</div>
                <div>Email:</div>
                <div>{{user.email}}</div>
                <div>Номер телефона:</div>
                <div>{{user.phone}}</div>
                <div>Количество товаров:</div>
                <div>{{count}}</div>
                <div class="generic-button">
                    {% if request.user == user %}
                    <a href="{% url 'supplies:add_supply' %}">Создать объявление</a>
                    {% else %}
                    <a href="{% url 'supplies:chat' user.username %}">Написать пользователю</a>
                    {% endif %}
                </div>
        </div>
        <hr class="profile-division">
        <div class="user-supplies">
            {% for supply in page_obj %}
                <a class="supply" href="{% url 'supplies:supply' supply.id %}">
                    {% if supply.image %}
                        {% thumbnail supply.image "200x200" crop="center" upscale=True as im %}
                            <img class="" src="{{ im.url }}">
                        {% endthumbnail %}
                        {% else %}
                        <img src="{% static 'img/no-image.jpeg' %}" width="200" height="200">
                    {% endif %}
                    <div class="supply_name">{{ supply.name }}</div>
                    <div class="price">{{ supply.price }}</div>
                    <div class="desc">{{ supply.desc }}</div>
                </a>
            {% endfor %}
        </div>
        <div class="grid-pagination">
            {% include "includes/paginator.html" %}
        </div>
    </section>
{% endblock %}

sellnbuy/templates/supplies/supply_page.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
    <section class="supply-page">
        {% if supply.image %}
        {% thumbnail supply.image "500x500" crop="center" upscale=True as im %}
        <img class="" src="{{ im.url }}">
        {% endthumbnail %}
        {% else %}
        <img src="{% static 'img/no-image.jpeg' %}" width="500" height="500">
        {% endif %}
        <div>Пользователь:</div>
        <a class="link" href="{% url 'supplies:profile' supply.user %}">{{ supply.user }}</a>
        <div>Название товара:</div>
        <div>{{ supply.name }}</div>
        <div>Цена товара:</div>
        <div>{{ supply.price }}</div>
        <div>Описание товара:</div>
        <div>{{ supply.desc }}</div>
        {% if request.user.is_authenticated and supply.user.id == request.user.id %}
        <div class="options">
            <a class="link" href="{% url 'supplies:change_supply' supply.id %}">Редактировать товар</a>
            <a class="link" href="{% url 'supplies:delete_supply' supply.id %}">Удалить товар</a>
        </div>
        {% endif %}
     </section>
    {% if request.user.is_authenticated and request.user != supply.user and not is_user_comment_exists %}
    <form method="POST" class='comment-form' action="{% url 'supplies:add_comment' supply.id %}">
        {% csrf_token %}
        {% for field in form %}
        <div class="comment-input">
            <label>{{ field.label_tag }}</label>
            <div>{{ field }}</div>
            {% if field.errors %}
            {% for error in field.errors %}
              <div class="form-error">{{ error }}</div>
            {% endfor %}
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="comment-button">Опубликовать комментарий</button>
    </form>
    {% endif %}
    {% if page_obj %}
    <div class="comments">
        <hr>
        {% for comment in page_obj %}
        <div class="comment">
            <a href="{% url 'supplies:profile' comment.user %}" class="link">{{comment.user}}</a>
            <div>Оценка пользователя: {{comment.rating}}/5</div>
            <div>Комментарий:</div>
            <div>{{comment.text}}</div>
            {% if request.user.is_authenticated and comment.user.id == request.user.id %}
            <div class="options">
                <a class="link" href="{% url 'supplies:change_comment' comment.id %}">Редактировать</a>
                <a class="link" href="{% url 'supplies:delete_comment' comment.id %}">Удалить</a>
            </div>
            {% endif %}
        </div>
        <hr>
        {% endfor %}
    </div>
    {% include 'includes/paginator.html' %}
    {% endif %}
{% endblock %}