sellnbuy/about/urls.py
from . import views
from django.urls import path

app_name = 'about'

urlpatterns = [
    path('about-author', views.author_page, name='author_page'),
    path('techs', views.techs, name='techs')
]

sellnbuy/sellnbuy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('users.urls')),
    path('', include('supplies.urls')),
    path('', include('about.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellnbuy/supplies/urls.py
from django.urls import path
from . import views

app_name = "supplies"

urlpatterns = [
    path('', views.main, name='index'),
    path('add-supply/', views.add_supply, name='add_supply'),
    path('messanger', views.messanger, name='messanger'),
    path('<int:id>/', views.view_supply, name='supply'),
    path('<int:id>/comment', views.add_comment, name='add_comment'),
    path('change-supply/<int:id>', views.change_supply, name='change_supply'),
    path('delete-supply/<int:id>', views.delete_supply, name='delete_supply'),
    path('change-comment/<int:id>', views.change_comment, name='change_comment'),
    path('delete-comment/<int:id>', views.delete_comment, name='delete_comment'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/chat', views.open_chat, name='chat'),
    path('<str:username>/chat/send-message', views.send_message, name='send_message'),
    ]

sellnbuy/users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, LoginView, \
    LogoutView

app_name = "users"

urlpatterns = [
    path('sign-up', views.SignUp.as_view(), name='sign_up'),
    path('password-reset', PasswordResetView.as_view(template_name="users/password_reset.html", success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset-done', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('login', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    ]

sellnbuy/templates/includes/footer.html
<div class="footer">
    <div><a class="link" href="{% url 'about:author_page' %}">Об авторе</a></div>
    <div><a class="link" href="{% url 'about:techs' %}">Технологии</a></div>
    <div>Торговая площадка sellNbuy © {% now 'Y' %}, все права защищены.</div>
</div>

sellnbuy/templates/includes/header.html
{% load static %}
<header class="page-header">
    <a href="{% url 'supplies:index' %}">
        <img src="{% static 'img/logo.png' %}" width="400" height="55">
    </a>
    <nav>
        <ul class="menu">
            {% if user.is_authenticated %}
                <li><a href="{% url 'supplies:messanger' %}">Мессенджер</a></li>
                <li><a href="{% url 'supplies:add_supply' %}">Создать объявление</a></li>
                <li><a href="{% url 'supplies:profile' user.username %}">Профиль</a></li>
                <li><a href="{% url 'users:logout' %}">Выйти</a></li>
            {% else %}
                <li><a href="{% url 'users:login' %}">Войти</a></li>
                <li><a href="{% url 'users:sign_up' %}">Зарегистрироваться</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

sellnbuy/templates/includes/paginator.html
<div class="pagination">
    {% if page_obj.has_previous %}
        <a class="page-switcher" href="?page=1">
        <div class="paginator">
            &laquo; В начало
        </div>
        </a>
        <a class="page-switcher" href="?page={{ page_obj.previous_page_number }}">
        <div class="paginator">
            Назад
        </div>
        </a>
        {% endif %}

        {% for page_number in paginator_page_numbers %}
            {% if page_number > 0 and page_number <= page_obj.paginator.num_pages %}
                <a class="page-switcher" href="?page={{page_number}}">
                    <div class="paginator">
                        {{page_number}}
                    </div>
                </a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a class="page-switcher" href="?page={{ page_obj.next_page_number }}">
            <div class="paginator">
                Вперед
            </div>
        </a>
        <a class="page-switcher" href="?page={{ page_obj.paginator.num_pages }}">
            <div class="paginator">
                В конец &raquo;
            </div>
        </a>
    {% endif %}
</div>